version: '3'
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    restart: always
    build: ./api:/app
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app